services:
  - type: web
    name: guandoudizhu
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
